const {
  Document, Packer, Paragraph, TextRun, Table, TableRow, TableCell,
  HeadingLevel, AlignmentType, BorderStyle, WidthType, ShadingType,
  NumberingFormat, PageOrientation, convertInchesToTwip, LevelFormat,
  Header, Footer, PageNumber, Tab, TabStopType, TabStopPosition
} = require('docx');
const fs = require('fs');

// ============================================================
// Helper functions
// ============================================================

function heading(text, level) {
  return new Paragraph({
    heading: level,
    spacing: { before: 240, after: 120 },
    children: [new TextRun({ text, font: 'Microsoft YaHei' })],
  });
}

function para(text, options = {}) {
  return new Paragraph({
    spacing: { after: 80, line: 360 },
    indent: options.indent ? { firstLine: convertInchesToTwip(0.3) } : undefined,
    children: [new TextRun({
      text,
      font: options.mono ? 'Consolas' : 'Microsoft YaHei',
      size: options.mono ? 20 : 22,
      ...options,
    })],
  });
}

function codeBlock(lines) {
  const children = [];
  if (typeof lines === 'string') lines = lines.split('\n');
  lines.forEach((line, i) => {
    if (i > 0) children.push(new TextRun({ break: 1 }));
    children.push(new TextRun({
      text: line || ' ',
      font: 'Consolas',
      size: 18,
    }));
  });
  return new Paragraph({
    spacing: { after: 120, line: 280 },
    shading: { type: ShadingType.SOLID, color: 'F5F5F5', fill: 'F5F5F5' },
    border: {
      left: { style: BorderStyle.SINGLE, size: 4, color: 'CCCCCC' },
    },
    indent: { left: convertInchesToTwip(0.3) },
    children,
  });
}

function bullet(text, level = 0) {
  return new Paragraph({
    spacing: { after: 40, line: 340 },
    indent: { left: convertInchesToTwip(0.3 + level * 0.3) },
    children: [
      new TextRun({ text: '• ', font: 'Microsoft YaHei', size: 22 }),
      new TextRun({ text, font: 'Microsoft YaHei', size: 22 }),
    ],
  });
}

function numberedItem(num, text, level = 0) {
  return new Paragraph({
    spacing: { after: 40, line: 340 },
    indent: { left: convertInchesToTwip(0.3 + level * 0.3) },
    children: [
      new TextRun({ text: `${num}. `, font: 'Microsoft YaHei', size: 22, bold: true }),
      new TextRun({ text, font: 'Microsoft YaHei', size: 22 }),
    ],
  });
}

function boldPara(boldText, normalText) {
  return new Paragraph({
    spacing: { after: 80, line: 360 },
    children: [
      new TextRun({ text: boldText, font: 'Microsoft YaHei', size: 22, bold: true }),
      new TextRun({ text: normalText, font: 'Microsoft YaHei', size: 22 }),
    ],
  });
}

function tip(type, text) {
  const colors = { info: '2196F3', warn: 'FF9800', success: '4CAF50', danger: 'F44336' };
  const icons = { info: '💡', warn: '⚠️', success: '✅', danger: '❌' };
  return new Paragraph({
    spacing: { after: 80, line: 360 },
    shading: { type: ShadingType.SOLID, color: colors[type], fill: colors[type] },
    indent: { left: convertInchesToTwip(0.2) },
    border: {
      left: { style: BorderStyle.SINGLE, size: 6, color: colors[type] },
    },
    children: [
      new TextRun({ text: `${icons[type]} `, font: 'Microsoft YaHei', size: 22 }),
      new TextRun({ text, font: 'Microsoft YaHei', size: 22 }),
    ],
  });
}

function emptyLine() {
  return new Paragraph({ spacing: { after: 80 }, children: [] });
}

// ============================================================
// Document Content
// ============================================================

const doc = new Document({
  creator: 'Claude AI Assistant',
  title: 'Minecraft 1.20.1 Fabric 模组开发完整流程',
  description: '从零开始的 Minecraft Fabric 模组开发指南',
  styles: {
    default: {
      document: {
        run: { font: 'Microsoft YaHei', size: 22 },
      },
    },
  },
  sections: [
    {
      properties: {
        page: {
          margin: {
            top: convertInchesToTwip(0.8),
            bottom: convertInchesToTwip(0.8),
            left: convertInchesToTwip(1.0),
            right: convertInchesToTwip(1.0),
          },
        },
      },
      headers: {
        default: new Header({
          children: [
            new Paragraph({
              alignment: AlignmentType.RIGHT,
              children: [
                new TextRun({ text: 'Minecraft 1.20.1 Fabric 模组开发流程', font: 'Microsoft YaHei', size: 16, color: '999999' }),
              ],
            }),
          ],
        }),
      },
      footers: {
        default: new Footer({
          children: [
            new Paragraph({
              alignment: AlignmentType.CENTER,
              children: [
                new TextRun({ text: '— ', font: 'Microsoft YaHei', size: 16, color: '999999' }),
                new TextRun({ children: [PageNumber.CURRENT], font: 'Microsoft YaHei', size: 16, color: '999999' }),
                new TextRun({ text: ' —', font: 'Microsoft YaHei', size: 16, color: '999999' }),
              ],
            }),
          ],
        }),
      },
      children: [
        // ==================== 封面 ====================
        emptyLine(), emptyLine(), emptyLine(), emptyLine(), emptyLine(),
        new Paragraph({
          alignment: AlignmentType.CENTER,
          spacing: { after: 120 },
          children: [new TextRun({ text: '🎮', size: 80 })],
        }),
        new Paragraph({
          alignment: AlignmentType.CENTER,
          spacing: { after: 200 },
          children: [new TextRun({
            text: 'Minecraft 1.20.1 Fabric\n模组开发完整流程',
            font: 'Microsoft YaHei',
            size: 52,
            bold: true,
            color: '2C3E50',
          })],
        }),
        new Paragraph({
          alignment: AlignmentType.CENTER,
          spacing: { after: 80 },
          children: [new TextRun({
            text: '从环境搭建到发布模组的全流程指南',
            font: 'Microsoft YaHei',
            size: 28,
            color: '7F8C8D',
          })],
        }),
        emptyLine(), emptyLine(),
        new Paragraph({
          alignment: AlignmentType.CENTER,
          spacing: { after: 40 },
          children: [new TextRun({
            text: '适用版本：Minecraft 1.20.1  |  Fabric Loader 0.14+  |  Fabric API',
            font: 'Microsoft YaHei',
            size: 22,
            color: '95A5A6',
          })],
        }),
        new Paragraph({
          alignment: AlignmentType.CENTER,
          children: [new TextRun({
            text: '文档版本：2024.06  |  更新日期：2026-06-08',
            font: 'Microsoft YaHei',
            size: 22,
            color: '95A5A6',
          })],
        }),

        // 分页
        new Paragraph({ pageBreakBefore: true, children: [] }),

        // ==================== 目录页 ====================
        heading('目录', HeadingLevel.HEADING_1),
        emptyLine(),
        ...[
          '第一章  环境准备',
          '    1.1 安装 JDK 17',
          '    1.2 安装 IntelliJ IDEA',
          '    1.3 安装 Fabric 开发插件',
          '第二章  项目创建',
          '    2.1 使用模板生成器创建项目',
          '    2.2 手动创建项目',
          '    2.3 项目结构详解',
          '第三章  模组核心配置',
          '    3.1 fabric.mod.json 详解',
          '    3.2 主类编写',
          '    3.3 build.gradle 与 gradle.properties',
          '第四章  添加自定义物品',
          '    4.1 注册物品',
          '    4.2 物品模型与纹理',
          '    4.3 物品语言文件',
          '    4.4 创造性标签页',
          '第五章  添加自定义方块',
          '    5.1 注册方块与方块物品',
          '    5.2 方块状态与模型',
          '    5.3 方块实体（BlockEntity）',
          '第六章  Mixin 注入',
          '    6.1 Mixin 概念与配置',
          '    6.2 常用注入类型',
          '    6.3 实战：修改生物掉落',
          '第七章  事件与网络',
          '    7.1 Fabric 事件系统',
          '    7.2 自定义网络包',
          '第八章  构建、测试与发布',
          '    8.1 Gradle 构建',
          '    8.2 调试技巧',
          '    8.3 发布到 CurseForge / Modrinth',
        ].map(t => new Paragraph({
          spacing: { after: 40, line: 340 },
          children: [new TextRun({
            text: t,
            font: 'Consolas',
            size: 20,
          })],
        })),

        // ==================== 第一章 ====================
        new Paragraph({ pageBreakBefore: true, children: [] }),
        heading('第一章  环境准备', HeadingLevel.HEADING_1),
        emptyLine(),

        heading('1.1  安装 JDK 17', HeadingLevel.HEADING_2),
        para('Minecraft 1.20.1 基于 Java 17 运行，因此必须安装 JDK 17。推荐使用 Eclipse Temurin（原 Adoptium）发行版。', { indent: true }),
        emptyLine(),
        boldPara('安装步骤：', ''),
        numberedItem(1, '访问 https://adoptium.net/download/'),
        numberedItem(2, '选择 "Temurin 17 (LTS)"，操作系统选择你的系统，架构选择 x64'),
        numberedItem(3, '下载 .msi 安装包（Windows）或 .pkg（macOS）'),
        numberedItem(4, '运行安装程序，勾选 "设置 JAVA_HOME 变量" 和 "添加到 PATH"'),
        numberedItem(5, '安装完成后，打开终端验证：'),
        emptyLine(),
        codeBlock('java -version\n# 应输出: openjdk version "17.0.x" ...\njavac -version\n# 应输出: javac 17.0.x'),
        emptyLine(),
        tip('success', '确保 JAVA_HOME 环境变量指向 JDK 17 的安装目录（例如 C:\\Program Files\\Eclipse Adoptium\\jdk-17.0.9.9-hotspot\\）。'),

        heading('1.2  安装 IntelliJ IDEA', HeadingLevel.HEADING_2),
        para('IntelliJ IDEA 是目前 Minecraft 模组开发的首选 IDE。社区版（Community Edition）免费且功能充足。', { indent: true }),
        emptyLine(),
        bullet('下载地址：https://www.jetbrains.com/idea/download/'),
        bullet('选择 Community Edition 即可，Ultimate 版的额外功能对模组开发并非必需'),
        bullet('安装时建议勾选 "Add Open Folder as Project" 和 ".java 文件关联"'),

        heading('1.3  安装 Fabric 开发插件', HeadingLevel.HEADING_2),
        para('Fabric 官方提供了 IntelliJ IDEA 插件，可以极大简化开发流程。', { indent: true }),
        emptyLine(),
        boldPara('安装方法：', ''),
        numberedItem(1, '打开 IntelliJ IDEA，进入 File → Settings → Plugins'),
        numberedItem(2, '搜索 "Minecraft Development"'),
        numberedItem(3, '安装由 "DemonWav" 开发的 Minecraft Development 插件'),
        numberedItem(4, '重启 IDE 使插件生效'),
        emptyLine(),
        tip('info', '该插件提供了 Fabric 项目模板、mixin 自动补全、fabric.mod.json 编辑辅助等功能，强烈推荐安装。'),

        // ==================== 第二章 ====================
        new Paragraph({ pageBreakBefore: true, children: [] }),
        heading('第二章  项目创建', HeadingLevel.HEADING_1),
        emptyLine(),

        heading('2.1  使用模板生成器创建项目（推荐）', HeadingLevel.HEADING_2),
        para('Fabric 官方提供了项目模板生成器，这是最推荐的创建方式。', { indent: true }),
        emptyLine(),
        boldPara('在线生成器方式：', ''),
        numberedItem(1, '打开浏览器访问 https://fabricmc.net/develop/template/'),
        numberedItem(2, '填写项目信息：'),
        bullet('Mod Name：你的模组名称（例如 MyAwesomeMod）'),
        bullet('Maven Group：你的 Maven 组名（例如 com.example）'),
        bullet('Mod ID：模组唯一标识符（例如 my-awesome-mod）'),
        bullet('Minecraft Version：选择 1.20.1'),
        numberedItem(3, '勾选需要的选项：'),
        bullet('Split sources (client/common/server)：推荐勾选，分离客户端和服务端代码'),
        bullet('Kotlin：如果不使用 Kotlin 则不勾选'),
        bullet('Data generation：如果需要数据生成则勾选'),
        numberedItem(4, '点击 "Download Template" 下载 ZIP 文件'),
        numberedItem(5, '解压到你的工作目录'),
        numberedItem(6, '用 IntelliJ IDEA 打开解压后的文件夹（作为 Gradle 项目导入）'),
        emptyLine(),

        boldPara('IDE 插件方式：', ''),
        numberedItem(1, '在 IntelliJ IDEA 中：File → New → Project'),
        numberedItem(2, '选择 "Minecraft" 类别 → "Fabric"'),
        numberedItem(3, '填写模组信息（同上）'),
        numberedItem(4, '点击 Finish，IDE 会自动生成项目结构'),
        emptyLine(),
        tip('warn', '首次导入 Gradle 项目时，IDE 会下载依赖（包括 Minecraft 反混淆的 JAR 文件），需要较长时间，请耐心等待并保持网络畅通。'),

        heading('2.2  手动创建项目', HeadingLevel.HEADING_2),
        para('如果不想使用模板生成器，也可以手动搭建。以下是最小化的项目结构：', { indent: true }),
        emptyLine(),
        codeBlock([
          'my-mod-project/',
          '├── build.gradle',
          '├── gradle.properties',
          '├── settings.gradle',
          '├── gradle/',
          '│   └── wrapper/',
          '│       ├── gradle-wrapper.jar',
          '│       └── gradle-wrapper.properties',
          '├── gradlew',
          '├── gradlew.bat',
          '└── src/',
          '    └── main/',
          '        ├── java/',
          '        │   └── com/example/mymod/',
          '        │       └── MyMod.java',
          '        └── resources/',
          '            ├── fabric.mod.json',
          '            ├── my-mod.mixins.json',
          '            └── assets/my-mod/',
          '                ├── lang/',
          '                │   └── en_us.json',
          '                └── textures/',
          '                    ├── item/',
          '                    └── block/',
        ]),

        heading('2.3  项目结构详解', HeadingLevel.HEADING_2),
        emptyLine(),
        boldPara('核心文件说明：', ''),
        emptyLine(),

        new Table({
          width: { size: 100, type: WidthType.PERCENTAGE },
          rows: [
            new TableRow({
              tableHeader: true,
              children: [
                new TableCell({ width: { size: 25, type: WidthType.PERCENTAGE }, shading: { fill: '2C3E50' }, children: [new Paragraph({ alignment: AlignmentType.CENTER, children: [new TextRun({ text: '文件/目录', bold: true, color: 'FFFFFF', font: 'Microsoft YaHei', size: 20 })] })] }),
                new TableCell({ width: { size: 75, type: WidthType.PERCENTAGE }, shading: { fill: '2C3E50' }, children: [new Paragraph({ alignment: AlignmentType.CENTER, children: [new TextRun({ text: '作用说明', bold: true, color: 'FFFFFF', font: 'Microsoft YaHei', size: 20 })] })] }),
              ],
            }),
            ...([
              ['build.gradle', 'Gradle 构建脚本，定义依赖、插件、任务等'],
              ['gradle.properties', 'Gradle 属性配置，包含模组版本、Minecraft 版本等变量'],
              ['settings.gradle', '项目设置，定义项目名和仓库源'],
              ['src/main/java/', 'Java 源代码目录'],
              ['src/main/resources/', '资源文件目录（JSON、纹理、模型等）'],
              ['fabric.mod.json', 'Fabric 模组元数据文件（核心配置）'],
              ['*.mixins.json', 'Mixin 配置文件，声明注入点和目标类'],
              ['assets/<modid>/lang/', '语言文件目录（国际化翻译）'],
              ['assets/<modid>/textures/', '纹理资源目录'],
              ['assets/<modid>/models/', '模型 JSON 文件目录'],
              ['assets/<modid>/blockstates/', '方块状态定义目录'],
            ].map(([file, desc]) => new TableRow({
              children: [
                new TableCell({ children: [new Paragraph({ children: [new TextRun({ text: file, font: 'Consolas', size: 19 })] })] }),
                new TableCell({ children: [new Paragraph({ children: [new TextRun({ text: desc, font: 'Microsoft YaHei', size: 20 })] })] }),
              ],
            }))),
          ],
        }),

        // ==================== 第三章 ====================
        new Paragraph({ pageBreakBefore: true, children: [] }),
        heading('第三章  模组核心配置', HeadingLevel.HEADING_1),
        emptyLine(),

        heading('3.1  fabric.mod.json 详解', HeadingLevel.HEADING_2),
        para('fabric.mod.json 是 Fabric 模组的核心元数据文件，位于 src/main/resources/ 下。这是模组的"身份证"。', { indent: true }),
        emptyLine(),
        codeBlock([
          '{',
          '  "schemaVersion": 1,',
          '  "id": "my-awesome-mod",',
          '  "version": "${version}",',
          '',
          '  "name": "My Awesome Mod",',
          '  "description": "这是一个示例模组！",',
          '  "authors": ["YourName"],',
          '  "contact": {',
          '    "homepage": "https://example.com",',
          '    "sources": "https://github.com/you/my-mod",',
          '    "issues": "https://github.com/you/my-mod/issues"',
          '  },',
          '  "license": "MIT",',
          '  "icon": "assets/my-awesome-mod/icon.png",',
          '',
          '  "environment": "*",',
          '  "entrypoints": {',
          '    "main": [',
          '      "com.example.mymod.MyMod"',
          '    ],',
          '    "client": [',
          '      "com.example.mymod.MyModClient"',
          '    ]',
          '  },',
          '  "mixins": [',
          '    "my-awesome-mod.mixins.json"',
          '  ],',
          '',
          '  "depends": {',
          '    "fabricloader": ">=0.14.21",',
          '    "minecraft": "~1.20.1",',
          '    "java": ">=17",',
          '    "fabric-api": ">=0.86.0"',
          '  },',
          '  "suggests": {',
          '    "modmenu": ">=7.0.0"',
          '  }',
          '}',
        ]),
        emptyLine(),
        boldPara('关键字段说明：', ''),
        bullet('id：模组唯一标识符，只能包含小写字母、数字、连字符和下划线'),
        bullet('version：使用 ${version} 引用 gradle.properties 中的版本号'),
        bullet('environment："*" 表示双端加载，"client" 仅客户端，"server" 仅服务端'),
        bullet('entrypoints：入口点声明，main 是双端入口，client 是客户端入口，server 是服务端入口'),
        bullet('mixins：引用的 Mixin 配置文件列表'),
        bullet('depends：硬依赖，必须满足版本要求。~1.20.1 表示兼容所有 1.20.x 次要版本'),
        bullet('suggests：软依赖，可选安装的推荐模组'),
        emptyLine(),
        tip('warn', 'Mod ID 一旦确定就不要更改，否则会导致存档中的物品/方块丢失！'),

        heading('3.2  主类编写', HeadingLevel.HEADING_2),
        para('所有 Fabric 模组都需要一个主类来实现 ModInitializer 接口。这个类在模组加载时被调用。', { indent: true }),
        emptyLine(),
        codeBlock([
          'package com.example.mymod;',
          '',
          'import net.fabricmc.api.ModInitializer;',
          'import net.fabricmc.fabric.api.itemgroup.v1.FabricItemGroup;',
          'import net.minecraft.item.ItemGroup;',
          'import net.minecraft.item.ItemStack;',
          'import net.minecraft.registry.Registries;',
          'import net.minecraft.registry.Registry;',
          'import net.minecraft.registry.RegistryKey;',
          'import net.minecraft.registry.RegistryKeys;',
          'import net.minecraft.text.Text;',
          'import net.minecraft.util.Identifier;',
          'import org.slf4j.Logger;',
          'import org.slf4j.LoggerFactory;',
          '',
          'public class MyMod implements ModInitializer {',
          '',
          '    // 模组ID常量，全局使用',
          '    public static final String MOD_ID = "my-awesome-mod";',
          '',
          '    // 日志记录器',
          '    public static final Logger LOGGER =',
          '        LoggerFactory.getLogger(MOD_ID);',
          '',
          '    @Override',
          '    public void onInitialize() {',
          '        LOGGER.info("My Awesome Mod 正在初始化！");',
          '',
          '        // 在这里注册物品、方块等',
          '        ModItems.registerModItems();',
          '        ModBlocks.registerModBlocks();',
          '',
          '        LOGGER.info("My Awesome Mod 初始化完成！");',
          '    }',
          '}',
        ]),
        emptyLine(),
        tip('info', 'onInitialize() 方法在 Minecraft 游戏实例启动时被调用。在这里执行所有注册操作（物品、方块、事件监听器等）。对于客户端专用的初始化，使用 ClientModInitializer 接口。'),

        heading('3.3  build.gradle 与 gradle.properties', HeadingLevel.HEADING_2),
        boldPara('build.gradle（核心构建脚本）：', ''),
        codeBlock([
          'plugins {',
          "    id 'fabric-loom' version '1.2-SNAPSHOT'",
          "    id 'maven-publish'",
          '}',
          '',
          "version = project.mod_version",
          "group = project.maven_group",
          '',
          'repositories {',
          '    // 添加额外的 Maven 仓库',
          '}',
          '',
          'dependencies {',
          '    // Fabric 基础依赖',
          "    minecraft \"com.mojang:minecraft:${project.minecraft_version}\"",
          "    mappings \"net.fabricmc:yarn:${project.yarn_mappings}:v2\"",
          "    modImplementation \"net.fabricmc:fabric-loader:${project.loader_version}\"",
          '',
          '    // Fabric API',
          "    modImplementation \"net.fabricmc.fabric-api:fabric-api:${project.fabric_version}\"",
          '}',
        ]),
        emptyLine(),
        boldPara('gradle.properties（版本变量集中管理）：', ''),
        codeBlock([
          'minecraft_version=1.20.1',
          'yarn_mappings=1.20.1+build.10',
          'loader_version=0.14.21',
          'fabric_version=0.86.0+1.20.1',
          '',
          'mod_version=1.0.0',
          'maven_group=com.example',
          'archives_base_name=my-awesome-mod',
        ]),
        emptyLine(),
        tip('info', '集中管理版本号可以避免在多处修改同一个值。Fabric Loom 是 Fabric 专用的 Gradle 插件，负责反编译 Minecraft、应用映射等。'),

        // ==================== 第四章 ====================
        new Paragraph({ pageBreakBefore: true, children: [] }),
        heading('第四章  添加自定义物品', HeadingLevel.HEADING_1),
        emptyLine(),

        heading('4.1  注册物品', HeadingLevel.HEADING_2),
        para('在 Minecraft 1.20.1 中，物品注册使用 Fabric 的 Registry API。推荐创建一个专门的 ModItems 类来集中管理所有物品。', { indent: true }),
        emptyLine(),
        codeBlock([
          'package com.example.mymod.item;',
          '',
          'import com.example.mymod.MyMod;',
          'import net.fabricmc.fabric.api.item.v1.FabricItemSettings;',
          'import net.minecraft.item.Item;',
          'import net.minecraft.registry.Registries;',
          'import net.minecraft.registry.Registry;',
          'import net.minecraft.util.Identifier;',
          '',
          'public class ModItems {',
          '',
          '    // 声明物品实例',
          '    public static final Item RUBY = registerItem(',
          '        "ruby",',
          '        new Item(new FabricItemSettings())',
          '    );',
          '',
          '    public static final Item RUBY_SWORD = registerItem(',
          '        "ruby_sword",',
          '        new SwordItem(',
          '            ModToolMaterial.RUBY,',
          '            3,           // 基础攻击伤害加成',
          '            -2.4f,       // 攻击速度修正',
          '            new FabricItemSettings()',
          '        )',
          '    );',
          '',
          '    // 注册方法',
          '    private static Item registerItem(',
          '            String name, Item item) {',
          '        return Registry.register(',
          '            Registries.ITEM,',
          '            new Identifier(MyMod.MOD_ID, name),',
          '            item',
          '        );',
          '    }',
          '',
          '    public static void registerModItems() {',
          '        MyMod.LOGGER.info(',
          '            "注册 " + MyMod.MOD_ID + " 的物品"',
          '        );',
          '    }',
          '}',
        ]),
        emptyLine(),
        boldPara('物品注册要点：', ''),
        bullet('每个物品都需要调用 Registry.register() 注册到 Registries.ITEM'),
        bullet('Identifier 格式为 "modid:item_name"，其中 modid 是你的模组ID'),
        bullet('FabricItemSettings 可以链式调用设置最大堆叠数、耐久度、食物属性等'),
        bullet('registerModItems() 方法在主类的 onInitialize() 中调用一次'),

        heading('4.2  物品模型与纹理', HeadingLevel.HEADING_2),
        para('物品在游戏中可见需要两个 JSON 文件：模型文件和纹理文件。', { indent: true }),
        emptyLine(),
        boldPara('模型文件 (assets/<modid>/models/item/ruby.json)：', ''),
        codeBlock([
          '{',
          '  "parent": "minecraft:item/generated",',
          '  "textures": {',
          '    "layer0": "my-awesome-mod:item/ruby"',
          '  }',
          '}',
        ]),
        emptyLine(),
        boldPara('纹理文件位置：', ''),
        codeBlock('assets/my-awesome-mod/textures/item/ruby.png'),
        emptyLine(),
        boldPara('纹理制作要点：', ''),
        bullet('纹理必须是 PNG 格式'),
        bullet('物品纹理推荐 16x16 像素（标准分辨率）'),
        bullet('可以制作 32x32 或更高分辨率的高清纹理，但需要额外的资源包配置'),
        bullet('纹理路径必须与模型 JSON 中的 layer0 路径一致'),

        heading('4.3  物品语言文件', HeadingLevel.HEADING_2),
        para('语言文件用于在游戏中显示物品的可读名称。', { indent: true }),
        emptyLine(),
        boldPara('英文 (assets/<modid>/lang/en_us.json)：', ''),
        codeBlock([
          '{',
          '  "item.my-awesome-mod.ruby": "Ruby",',
          '  "item.my-awesome-mod.ruby_sword": "Ruby Sword",',
          '  "itemGroup.my-awesome-mod.main": "My Awesome Mod"',
          '}',
        ]),
        emptyLine(),
        boldPara('中文 (assets/<modid>/lang/zh_cn.json)：', ''),
        codeBlock([
          '{',
          '  "item.my-awesome-mod.ruby": "红宝石",',
          '  "item.my-awesome-mod.ruby_sword": "红宝石剑",',
          '  "itemGroup.my-awesome-mod.main": "我的超棒模组"',
          '}',
        ]),
        emptyLine(),
        boldPara('翻译键命名规则：', ''),
        bullet('物品：item.<modid>.<item_name>'),
        bullet('方块：block.<modid>.<block_name>'),
        bullet('物品组：itemGroup.<modid>.<group_name>'),
        bullet('提示信息：tooltip.<modid>.<key>'),

        heading('4.4  创造性标签页', HeadingLevel.HEADING_2),
        para('为你的模组添加一个专属的创造性模式标签页，方便玩家查找物品。', { indent: true }),
        emptyLine(),
        codeBlock([
          '// 在 MyMod.java 中添加：',
          'public static final RegistryKey<ItemGroup> ITEM_GROUP =',
          '    RegistryKey.of(',
          '        RegistryKeys.ITEM_GROUP,',
          '        new Identifier(MOD_ID, "main")',
          '    );',
          '',
          '// 在 onInitialize() 中注册：',
          'Registry.register(',
          '    Registries.ITEM_GROUP,',
          '    ITEM_GROUP,',
          '    FabricItemGroup.builder()',
          '        .icon(() -> new ItemStack(ModItems.RUBY))',
          '        .displayName(Text.translatable(',
          '            "itemGroup.my-awesome-mod.main"))',
          '        .entries((displayContext, entries) -> {',
          '            entries.add(ModItems.RUBY);',
          '            entries.add(ModItems.RUBY_SWORD);',
          '            // 添加所有物品到这里',
          '        })',
          '        .build()',
          ');',
        ]),

        // ==================== 第五章 ====================
        new Paragraph({ pageBreakBefore: true, children: [] }),
        heading('第五章  添加自定义方块', HeadingLevel.HEADING_1),
        emptyLine(),

        heading('5.1  注册方块与方块物品', HeadingLevel.HEADING_2),
        para('方块需要同时注册 Block 和对应的 BlockItem（方块物品形式），这样玩家才能在背包中持有和放置方块。', { indent: true }),
        emptyLine(),
        codeBlock([
          'package com.example.mymod.block;',
          '',
          'import com.example.mymod.MyMod;',
          'import net.fabricmc.fabric.api.item.v1.FabricItemSettings;',
          'import net.fabricmc.fabric.api.object.builder.v1.',
          '    block.FabricBlockSettings;',
          'import net.minecraft.block.Block;',
          'import net.minecraft.block.Blocks;',
          'import net.minecraft.item.BlockItem;',
          'import net.minecraft.item.Item;',
          'import net.minecraft.registry.Registries;',
          'import net.minecraft.registry.Registry;',
          'import net.minecraft.util.Identifier;',
          '',
          'public class ModBlocks {',
          '',
          '    public static final Block RUBY_BLOCK = registerBlock(',
          '        "ruby_block",',
          '        new Block(FabricBlockSettings',
          '            .copyOf(Blocks.IRON_BLOCK)    // 复制铁块的属性',
          '            .requiresTool()               // 需要工具挖掘',
          '            .strength(5.0f, 6.0f)  // 硬度和抗爆性',
          '        )',
          '    );',
          '',
          '    private static Block registerBlock(',
          '            String name, Block block) {',
          '        // 先注册方块物品',
          '        registerBlockItem(name, block);',
          '        // 再注册方块',
          '        return Registry.register(',
          '            Registries.BLOCK,',
          '            new Identifier(MyMod.MOD_ID, name),',
          '            block',
          '        );',
          '    }',
          '',
          '    private static Item registerBlockItem(',
          '            String name, Block block) {',
          '        return Registry.register(',
          '            Registries.ITEM,',
          '            new Identifier(MyMod.MOD_ID, name),',
          '            new BlockItem(',
          '                block,',
          '                new FabricItemSettings()',
          '            )',
          '        );',
          '    }',
          '',
          '    public static void registerModBlocks() {',
          '        MyMod.LOGGER.info(',
          '            "注册 " + MyMod.MOD_ID + " 的方块"',
          '        );',
          '    }',
          '}',
        ]),

        heading('5.2  方块状态与模型', HeadingLevel.HEADING_2),
        para('方块在游戏中渲染需要三个资源文件：方块状态 JSON、方块模型 JSON、物品模型 JSON。', { indent: true }),
        emptyLine(),
        boldPara('方块状态文件 (assets/<modid>/blockstates/ruby_block.json)：', ''),
        codeBlock([
          '{',
          '  "variants": {',
          '    "": {',
          '      "model": "my-awesome-mod:block/ruby_block"',
          '    }',
          '  }',
          '}',
        ]),
        emptyLine(),
        boldPara('方块模型 (assets/<modid>/models/block/ruby_block.json)：', ''),
        codeBlock([
          '{',
          '  "parent": "minecraft:block/cube_all",',
          '  "textures": {',
          '    "all": "my-awesome-mod:block/ruby_block"',
          '  }',
          '}',
        ]),
        emptyLine(),
        boldPara('方块物品模型 (assets/<modid>/models/item/ruby_block.json)：', ''),
        codeBlock([
          '{',
          '  "parent": "my-awesome-mod:block/ruby_block"',
          '}',
        ]),
        emptyLine(),
        tip('info', '方块物品模型通常直接指向方块模型（parent），这样可以保持物品栏中的方块外观与放置后的方块一致。'),

        heading('5.3  方块实体（BlockEntity）', HeadingLevel.HEADING_2),
        para('方块实体用于存储方块级别的数据（如容器中的物品、熔炉的燃烧进度等）。创建需要两个类：Block 类 和 BlockEntity 类。', { indent: true }),
        emptyLine(),
        boldPara('BlockEntity 类的基本框架：', ''),
        codeBlock([
          'package com.example.mymod.block.entity;',
          '',
          'import com.example.mymod.ModBlocks;',
          'import net.minecraft.block.BlockState;',
          'import net.minecraft.block.entity.BlockEntity;',
          'import net.minecraft.nbt.NbtCompound;',
          'import net.minecraft.network.listener.',
          '    ClientPlayPacketListener;',
          'import net.minecraft.network.packet.',
          '    Packet;',
          'import net.minecraft.network.packet.s2c.play.',
          '    BlockEntityUpdateS2CPacket;',
          'import net.minecraft.util.math.BlockPos;',
          '',
          'public class MyBlockEntity extends BlockEntity {',
          '',
          '    public MyBlockEntity(',
          '            BlockPos pos, BlockState state) {',
          '        super(ModBlockEntities.MY_BLOCK_ENTITY,',
          '              pos, state);',
          '    }',
          '',
          '    @Override',
          '    public void writeNbt(NbtCompound nbt) {',
          '        super.writeNbt(nbt);',
          '        // 保存数据',
          '    }',
          '',
          '    @Override',
          '    public void readNbt(NbtCompound nbt) {',
          '        super.readNbt(nbt);',
          '        // 读取数据',
          '    }',
          '}',
        ]),
        emptyLine(),
        tip('warn', '方块实体类型（BlockEntityType）也需要注册。创建方式：BlockEntityType.Builder.create(MyBlockEntity::new, ModBlocks.MY_BLOCK).build(null)，然后通过 Registry.register() 注册。'),

        // ==================== 第六章 ====================
        new Paragraph({ pageBreakBefore: true, children: [] }),
        heading('第六章  Mixin 注入', HeadingLevel.HEADING_1),
        emptyLine(),

        heading('6.1  Mixin 概念与配置', HeadingLevel.HEADING_2),
        para('Mixin 是 Fabric 的核心特性，允许你在运行时修改 Minecraft 源代码的行为（方法注入、字段访问、接口添加等），无需直接修改 Minecraft 的代码。', { indent: true }),
        emptyLine(),
        boldPara('Mixin 配置文件 (<modid>.mixins.json)：', ''),
        codeBlock([
          '{',
          '  "required": true,',
          '  "minVersion": "0.8",',
          '  "package": "com.example.mymod.mixin",',
          '  "compatibilityLevel": "JAVA_17",',
          '  "mixins": [',
          '    "EntityMixin",',
          '    "LivingEntityMixin"',
          '  ],',
          '  "client": [',
          '    "client.TitleScreenMixin"',
          '  ],',
          '  "server": [],',
          '  "injectors": {',
          '    "defaultRequire": 1',
          '  }',
          '}',
        ]),
        emptyLine(),
        boldPara('配置说明：', ''),
        bullet('required：是否为必须的 Mixin，true 表示 Mixin 失败则模组加载失败'),
        bullet('package：Mixin 类所在的 Java 包名'),
        bullet('compatibilityLevel：Java 版本兼容性（1.20.1 使用 JAVA_17）'),
        bullet('mixins：双端（客户端+服务端）生效的 Mixin 类列表'),
        bullet('client：仅客户端生效的 Mixin 类列表'),
        bullet('server：仅服务端生效的 Mixin 类列表'),

        heading('6.2  常用注入类型', HeadingLevel.HEADING_2),
        emptyLine(),
        boldPara('@Inject —— 注入到方法中：', '在目标方法的指定位置插入代码。'),
        codeBlock([
          '@Mixin(PlayerEntity.class)',
          'public class PlayerEntityMixin {',
          '',
          '    @Inject(',
          '        method = "tick",',
          '        at = @At("HEAD")',
          '    )',
          '    private void onTick(',
          '            CallbackInfo info) {',
          '        // 每个 tick 都会执行这里的代码',
          '        // 目标方法执行前触发 (HEAD)',
          '    }',
          '}',
        ]),
        emptyLine(),
        boldPara('@Overwrite —— 完全覆盖方法：', ''),
        codeBlock([
          '@Mixin(LivingEntity.class)',
          'public class LivingEntityMixin {',
          '',
          '    @Overwrite',
          '    public boolean isGlowing() {',
          '        // 完全替换原方法',
          '        return true;',
          '    }',
          '}',
        ]),
        emptyLine(),
        boldPara('@Accessor —— 访问私有字段：', ''),
        codeBlock([
          '@Mixin(PlayerEntity.class)',
          'public interface PlayerEntityAccessor {',
          '',
          '    @Accessor("sleepTimer")',
          '    int getSleepTimer();',
          '',
          '    @Accessor("sleepTimer")',
          '    void setSleepTimer(int value);',
          '}',
        ]),
        emptyLine(),
        boldPara('@ModifyVariable —— 修改变量值：', ''),
        codeBlock([
          '@Mixin(PlayerEntity.class)',
          'public class PlayerEntityMixin {',
          '',
          '    @ModifyVariable(',
          '        method = "attack",',
          '        at = @At("STORE"),',
          '        ordinal = 0',
          '    )',
          '    private float modifyDamage(float original) {',
          '        // 将伤害值翻倍',
          '        return original * 2f;',
          '    }',
          '}',
        ]),
        emptyLine(),
        boldPara('注入位置 (@At) 常用值：', ''),
        bullet('HEAD —— 方法的最开始'),
        bullet('RETURN —— 方法返回前'),
        bullet('INVOKE —— 调用某个方法时'),
        bullet('TAIL —— 方法末尾（在返回前）'),
        bullet('INVOKE_ASSIGN —— 调用方法并赋值后'),

        heading('6.3  实战：修改生物掉落', HeadingLevel.HEADING_2),
        para('以下示例展示如何通过 Mixin 让所有生物死亡时额外掉落一枚钻石。', { indent: true }),
        emptyLine(),
        codeBlock([
          '@Mixin(LivingEntity.class)',
          'public abstract class LivingEntityMixin {',
          '',
          '    @Inject(',
          '        method = "dropLoot",',
          '        at = @At(',
          '            value = "INVOKE",',
          '            target = "Lnet/minecraft/entity/',
          '                     LivingEntity;',
          '                     shouldDropLoot()Z"',
          '        ),',
          '        cancellable = false',
          '    )',
          '    private void onDropLoot(',
          '            DamageSource source,',
          '            boolean causedByPlayer,',
          '            CallbackInfo ci) {',
          '',
          '        LivingEntity self =',
          '            (LivingEntity) (Object) this;',
          '',
          '        // 创建钻石掉落物',
          '        ItemEntity diamond = new ItemEntity(',
          '            self.getWorld(),',
          '            self.getX(),',
          '            self.getY(),',
          '            self.getZ(),',
          '            new ItemStack(Items.DIAMOND)',
          '        );',
          '',
          '        // 生成到世界中',
          '        self.getWorld().spawnEntity(diamond);',
          '    }',
          '}',
        ]),
        emptyLine(),
        tip('warn', '使用 @Inject 时，注意 cancellable = true 会阻止目标方法的执行。如果你只想添加额外逻辑而不阻止原方法，设置为 false。'),

        // ==================== 第七章 ====================
        new Paragraph({ pageBreakBefore: true, children: [] }),
        heading('第七章  事件与网络', HeadingLevel.HEADING_1),
        emptyLine(),

        heading('7.1  Fabric 事件系统', HeadingLevel.HEADING_2),
        para('Fabric API 提供了丰富的事件系统，让你可以为各种游戏事件注册监听器。', { indent: true }),
        emptyLine(),
        boldPara('常用事件示例：', ''),
        emptyLine(),
        codeBlock([
          '// ====== 玩家登录事件 ======',
          'ServerPlayConnectionEvents.JOIN.register(',
          '    (handler, sender, server) -> {',
          '        server.getPlayerManager().broadcast(',
          '            Text.literal(',
          '                handler.getPlayer().getName()',
          '                + " 加入了服务器！"',
          '            ),',
          '            false',
          '        );',
          '    }',
          ');',
          '',
          '// ====== 方块放置事件 ======',
          'UseBlockCallback.EVENT.register(',
          '    (player, world, hand, hitResult) -> {',
          '        BlockPos pos = hitResult.getBlockPos();',
          '        player.sendMessage(',
          '            Text.literal("你点击了: " + pos),',
          '            true',
          '        );',
          '        return ActionResult.PASS;',
          '    }',
          ');',
          '',
          '// ====== 攻击实体事件 ======',
          'AttackEntityCallback.EVENT.register(',
          '    (player, world, hand, entity, result) -> {',
          '        player.sendMessage(',
          '            Text.literal("你攻击了: "',
          '                + entity.getName().getString()),',
          '            true',
          '        );',
          '        return ActionResult.PASS;',
          '    }',
          ');',
        ]),
        emptyLine(),
        boldPara('事件回调的返回值含义：', ''),
        bullet('ActionResult.PASS —— 继续执行原版逻辑，不做干预'),
        bullet('ActionResult.SUCCESS —— 取消原版逻辑（对于可取消的事件）'),
        bullet('ActionResult.FAIL —— 取消原版逻辑并可能显示 "使用失败" 的效果'),
        emptyLine(),
        boldPara('常用事件类：', ''),
        bullet('ServerPlayConnectionEvents —— 玩家连接/断开事件'),
        bullet('ServerTickEvents —— 服务端 Tick 事件'),
        bullet('UseBlockCallback / UseItemCallback —— 方块/物品使用事件'),
        bullet('AttackEntityCallback —— 攻击实体事件'),
        bullet('PlayerBlockBreakEvents —— 方块破坏事件'),
        bullet('ServerLivingEntityEvents —— 实体相关事件'),

        heading('7.2  自定义网络包', HeadingLevel.HEADING_2),
        para('当需要在客户端和服务端之间传输自定义数据时，使用 Fabric Networking API。', { indent: true }),
        emptyLine(),
        boldPara('注册网络通道：', ''),
        codeBlock([
          'import net.fabricmc.fabric.api.networking.v1.',
          '    ServerPlayNetworking;',
          'import net.fabricmc.fabric.api.networking.v1.',
          '    PacketByteBufs;',
          '',
          '// 定义数据包ID',
          'public static final Identifier',
          '    MY_PACKET_ID = new Identifier(',
          '        MyMod.MOD_ID, "my_packet"',
          '    );',
          '',
          '// 在 onInitialize() 中注册接收端（服务端）',
          'ServerPlayNetworking.',
          '    registerGlobalReceiver(',
          '        MY_PACKET_ID,',
          '        (server, player, handler, buf, sender) -> {',
          '            // 从客户端收到的数据处理',
          '            String message = buf.readString();',
          '            server.execute(() -> {',
          '                player.sendMessage(',
          '                    Text.literal(',
          '                        "服务端收到: " + message',
          '                    )',
          '                );',
          '            });',
          '        }',
          '    );',
        ]),
        emptyLine(),
        boldPara('从客户端发送数据包：', ''),
        codeBlock([
          'import net.fabricmc.fabric.api.networking.v1.',
          '    ClientPlayNetworking;',
          '',
          '// 在客户端代码中发送',
          'PacketByteBuf buf = PacketByteBufs.create();',
          'buf.writeString("Hello from Client!");',
          'ClientPlayNetworking.send(MY_PACKET_ID, buf);',
        ]),
        emptyLine(),
        tip('info', '数据包的读和写顺序必须完全一致。使用 PacketByteBuf 提供的方法（writeString/readString, writeInt/readInt 等）进行序列化。'),

        // ==================== 第八章 ====================
        new Paragraph({ pageBreakBefore: true, children: [] }),
        heading('第八章  构建、测试与发布', HeadingLevel.HEADING_1),
        emptyLine(),

        heading('8.1  Gradle 构建', HeadingLevel.HEADING_2),
        para('使用 Gradle 将模组编译打包为 .jar 文件。', { indent: true }),
        emptyLine(),
        boldPara('常用 Gradle 命令（在项目根目录执行）：', ''),
        emptyLine(),
        new Table({
          width: { size: 100, type: WidthType.PERCENTAGE },
          rows: [
            new TableRow({
              tableHeader: true,
              children: [
                new TableCell({ width: { size: 40, type: WidthType.PERCENTAGE }, shading: { fill: '2C3E50' }, children: [new Paragraph({ alignment: AlignmentType.CENTER, children: [new TextRun({ text: '命令', bold: true, color: 'FFFFFF', font: 'Consolas', size: 19 })] })] }),
                new TableCell({ width: { size: 60, type: WidthType.PERCENTAGE }, shading: { fill: '2C3E50' }, children: [new Paragraph({ alignment: AlignmentType.CENTER, children: [new TextRun({ text: '说明', bold: true, color: 'FFFFFF', font: 'Microsoft YaHei', size: 20 })] })] }),
              ],
            }),
            ...[
              ['./gradlew build', '编译并构建模组 JAR 文件（输出到 build/libs/）'],
              ['./gradlew runClient', '启动 Minecraft 客户端并加载模组（调试用）'],
              ['./gradlew runServer', '启动 Minecraft 服务端并加载模组'],
              ['./gradlew clean', '清除构建缓存'],
              ['./gradlew remapJar', '仅生成映射后的 JAR'],
              ['./gradlew genSources', '生成带注释的 Minecraft 源代码'],
            ].map(([cmd, desc]) => new TableRow({
              children: [
                new TableCell({ children: [new Paragraph({ children: [new TextRun({ text: cmd, font: 'Consolas', size: 18 })] })] }),
                new TableCell({ children: [new Paragraph({ children: [new TextRun({ text: desc, font: 'Microsoft YaHei', size: 20 })] })] }),
              ],
            })),
          ],
        }),
        emptyLine(),
        boldPara('构建产物：', ''),
        bullet('build/libs/<modid>-<version>.jar —— 供玩家使用的模组文件'),
        bullet('build/libs/<modid>-<version>-sources.jar —— 源代码 JAR（可选，发布时提供）'),
        bullet('build/libs/<modid>-<version>-dev.jar —— 开发版 JAR（包含未混淆代码）'),

        heading('8.2  调试技巧', HeadingLevel.HEADING_2),
        emptyLine(),
        boldPara('日志输出：', ''),
        codeBlock([
          '// 使用 SLF4J 日志',
          'LOGGER.info("信息: {}", someVariable);',
          'LOGGER.warn("警告！");',
          'LOGGER.error("错误: ", exception);',
          'LOGGER.debug("调试: {}", value); // 需要在 gradle.properties 中启用',
        ]),
        emptyLine(),
        boldPara('IntelliJ IDEA 调试配置：', ''),
        numberedItem(1, '在 Gradle 面板中，展开 Tasks → fabric'),
        numberedItem(2, '右键 runClient → Debug（或点击绿色甲虫图标）'),
        numberedItem(3, '在代码中设置断点（点击行号旁边的空白区域）'),
        numberedItem(4, '当游戏运行到断点处会自动暂停，可以查看变量值、调用栈等'),
        emptyLine(),
        boldPara('常见调试场景：', ''),
        bullet('物品/方块不显示：检查 Registry 注册是否正确，模型 JSON 和纹理文件是否存在'),
        bullet('Mixin 不生效：检查 .mixins.json 中是否添加了 Mixin 类名，@At 位置是否正确'),
        bullet('纹理丢失：检查纹理 PNG 路径是否与模型 JSON 中的路径完全匹配'),
        bullet('崩溃：查看 crash-reports 目录中的崩溃报告，定位出错代码位置'),
        emptyLine(),
        tip('warn', '修改 Mixin 或资源文件后，建议执行 ./gradlew clean 清除缓存再重新构建，避免旧缓存导致问题。'),

        heading('8.3  发布到 CurseForge / Modrinth', HeadingLevel.HEADING_2),
        para('将模组发布到主流平台，让更多玩家能够使用你的模组。', { indent: true }),
        emptyLine(),
        boldPara('发布前检查清单：', ''),
        bullet('☐ 版本号正确设置（gradle.properties 中的 mod_version）'),
        bullet('☐ 所有物品、方块都有对应的中英文语言文件'),
        bullet('☐ 没有遗留的调试日志输出'),
        bullet('☐ 在纯净的 Minecraft 实例中测试过模组（只安装 Fabric API 和你的模组）'),
        bullet('☐ 编写了 README.md 说明模组功能和使用方法'),
        bullet('☐ 截图/视频展示模组效果'),
        bullet('☐ 确定开源协议（LICENSE 文件）'),
        emptyLine(),
        boldPara('发布流程 CurseForge：', ''),
        numberedItem(1, '访问 https://authors.curseforge.com/ 创建作者账号'),
        numberedItem(2, '创建新项目（Create Project）'),
        numberedItem(3, '填写项目信息：名称、摘要、描述、分类（Fabric）、Logo'),
        numberedItem(4, '上传 JAR 文件，填写版本号、支持的 Minecraft 版本'),
        numberedItem(5, '标记依赖关系（Fabric API 为必选依赖）'),
        numberedItem(6, '提交审核，等待通过'),
        emptyLine(),
        boldPara('发布流程 Modrinth：', ''),
        numberedItem(1, '访问 https://modrinth.com/ 注册账号'),
        numberedItem(2, '创建新项目（New Project）'),
        numberedItem(3, '填写模组信息，选择 Loader 为 "Fabric"'),
        numberedItem(4, '创建新版本（Create Version），上传 JAR 文件'),
        numberedItem(5, '指定支持的 Minecraft 版本和依赖'),
        numberedItem(6, '发布（Modrinth 通常无需审核，即时上线）'),
        emptyLine(),
        tip('info', '推荐同时发布到两个平台以覆盖更多玩家。可以使用 CurseGradle 和 Minotaur 这两个 Gradle 插件实现自动发布。'),

        // ==================== 附录 ====================
        new Paragraph({ pageBreakBefore: true, children: [] }),
        heading('附录  快速参考', HeadingLevel.HEADING_1),
        emptyLine(),

        heading('A. 常用类速查表', HeadingLevel.HEADING_2),
        emptyLine(),
        new Table({
          width: { size: 100, type: WidthType.PERCENTAGE },
          rows: [
            new TableRow({
              tableHeader: true,
              children: [
                new TableCell({ width: { size: 30, type: WidthType.PERCENTAGE }, shading: { fill: '2C3E50' }, children: [new Paragraph({ alignment: AlignmentType.CENTER, children: [new TextRun({ text: 'Yarn 类名', bold: true, color: 'FFFFFF', font: 'Consolas', size: 19 })] })] }),
                new TableCell({ width: { size: 70, type: WidthType.PERCENTAGE }, shading: { fill: '2C3E50' }, children: [new Paragraph({ alignment: AlignmentType.CENTER, children: [new TextRun({ text: '说明', bold: true, color: 'FFFFFF', font: 'Microsoft YaHei', size: 20 })] })] }),
              ],
            }),
            ...[
              ['net.minecraft.item.Item', '物品基类'],
              ['net.minecraft.block.Block', '方块基类'],
              ['net.minecraft.item.BlockItem', '方块对应的物品形式'],
              ['net.minecraft.item.SwordItem', '剑类物品'],
              ['net.minecraft.item.ToolItem', '工具物品基类'],
              ['net.minecraft.item.ArmorItem', '护甲物品'],
              ['net.minecraft.item.Item.Settings', '物品属性设置（Fabric 扩展：FabricItemSettings）'],
              ['net.minecraft.block.AbstractBlock.Settings', '方块属性设置（Fabric 扩展：FabricBlockSettings）'],
              ['net.minecraft.util.Identifier', '资源标识符（modid:path 格式）'],
              ['net.minecraft.registry.Registry', '注册表操作'],
              ['net.minecraft.registry.Registries', '所有注册表的入口'],
              ['net.minecraft.item.ItemGroup', '创造性标签页'],
              ['net.minecraft.text.Text', '文本组件'],
            ].map(([cls, desc]) => new TableRow({
              children: [
                new TableCell({ children: [new Paragraph({ children: [new TextRun({ text: cls, font: 'Consolas', size: 17 })] })] }),
                new TableCell({ children: [new Paragraph({ children: [new TextRun({ text: desc, font: 'Microsoft YaHei', size: 20 })] })] }),
              ],
            })),
          ],
        }),
        emptyLine(),

        heading('B. 常用 Fabric API 模块', HeadingLevel.HEADING_2),
        emptyLine(),
        bullet('fabric-api-base：Fabric API 基础设施'),
        bullet('fabric-item-api-v1：物品扩展 API（自定义物品设置、燃料注册等）'),
        bullet('fabric-object-builder-api-v1：方块/实体构建器 API'),
        bullet('fabric-rendering-v1：渲染扩展 API'),
        bullet('fabric-networking-api-v1：网络通信 API'),
        bullet('fabric-registry-sync-v0：注册表同步 API'),
        bullet('fabric-resource-loader-v0：资源加载器 API'),
        bullet('fabric-key-binding-api-v1：按键绑定 API'),
        bullet('fabric-events-lifecycle-v0：生命周期事件 API'),
        emptyLine(),

        heading('C. 推荐学习资源', HeadingLevel.HEADING_2),
        emptyLine(),
        boldPara('官方文档：', ''),
        bullet('Fabric Wiki：https://fabricmc.net/wiki/'),
        bullet('Fabric API 文档：https://fabricmc.net/develop/'),
        bullet('Mixin 文档：https://github.com/SpongePowered/Mixin/wiki'),
        emptyLine(),
        boldPara('社区资源：', ''),
        bullet('Fabric Discord：https://discord.gg/v6v4pMv（官方社区，可获取技术支持）'),
        bullet('GitHub 开源模组参考：搜索 "fabric-example-mod" 或浏览热门 Fabric 模组源码'),
        bullet('B站教程：搜索 "Minecraft Fabric 模组开发"'),
        emptyLine(),
        boldPara('工具推荐：', ''),
        bullet('Blockbench —— 免费开源的 3D 模型编辑器，可用于创建自定义方块/实体模型'),
        bullet('MCreator —— 可视化模组制作工具（适合零编程基础，但对 Fabric 支持有限）'),
        bullet('JSON Formatter —— 辅助编写和校验 JSON 配置文件'),

        // 结尾
        emptyLine(), emptyLine(),
        new Paragraph({
          alignment: AlignmentType.CENTER,
          border: {
            top: { style: BorderStyle.SINGLE, size: 2, color: 'CCCCCC' },
          },
          spacing: { before: 200, after: 80 },
          children: [new TextRun({
            text: '— 文档结束 —',
            font: 'Microsoft YaHei',
            size: 22,
            color: '95A5A6',
          })],
        }),
        new Paragraph({
          alignment: AlignmentType.CENTER,
          children: [new TextRun({
            text: '祝你的 Minecraft 模组开发之旅顺利！🎮✨',
            font: 'Microsoft YaHei',
            size: 24,
            color: '2C3E50',
          })],
        }),
      ],
    },
  ],
});

// ============================================================
// Generate the file
// ============================================================

const outputPath = 'E:/Claude/Minecraft_1.20.1_Fabric_模组开发流程.docx';

Packer.toBuffer(doc).then(buffer => {
  fs.writeFileSync(outputPath, buffer);
  console.log(`✅ 文档已生成: ${outputPath}`);
  console.log(`📄 文件大小: ${(buffer.length / 1024).toFixed(1)} KB`);
}).catch(err => {
  console.error('❌ 生成失败:', err);
  process.exit(1);
});
